include:
  # Стандартные прошивки
  - board: xiao_ble
    shield: ergonaut_one_left
  - board: xiao_ble
    shield: ergonaut_one_right

  # Прошивки с ZMK Studio
  - board: xiao_ble
    shield: ergonaut_one_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_left_studio
  - board: xiao_ble
    shield: ergonaut_one_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_right_studio

  # Утилита сброса настроек
  - board: xiao_ble
    shield: settings_reset
